config/routes.rb
SecretShareAjax::Application.routes.draw do
  resources :secrets, :only => [:create]
  resources :users, :only => [:create, :new, :show, :index] do
    resources :secrets, :only => [:new]
    resource :friendship, :only => [:create, :destroy]
  end
  resource :session, :only => [:create, :destroy, :new]
  root :to => "users#show"
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :in_friend_id, :out_friend_id
  validates :in_friend_id, :out_friend_id, :presence => true

  belongs_to(
    :in_friend,
    :class_name => "User"
  )

  belongs_to(
    :out_friend,
    :class_name => "User"
  )

  def self.can_friend?(out_friend_id, in_friend_id)
    !Friendship.exists?({:out_friend_id => out_friend_id,
                        :in_friend_id => in_friend_id})
  end

  def self.can_unfriend?(out_friend_id, in_friend_id)
    self.can_friend?(out_friend_id, in_friend_id)
  end
end

app/models/secret.rb
class Secret < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :title, :tag_ids

  belongs_to :author, :class_name => "User"
  belongs_to :recipient, :class_name => "User"

  has_many :secret_taggings
  has_many :tags, :through => :secret_taggings, :source => :tag

  validates :author_id, :recipient_id, :title, :presence => true
end

app/models/secret_tagging.rb
class SecretTagging < ActiveRecord::Base
  attr_accessible :secret_id, :tag_id
  validates :secret_id, :tag_id, :presence => true

  belongs_to :secret
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => :true, :uniqueness => true

  has_many :secret_taggings
  has_many :secrets, :through => :secret_taggings, :source => :secret

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  has_many(
    :authored_secrets,
    :class_name => "Secret",
    :foreign_key => :author_id
  )

  has_many(
    :received_secrets,
    :class_name => "Secret",
    :foreign_key => :recipient_id
  )

  has_many(
    :out_friendships,
    :foreign_key => :in_friend_id,
    :class_name => "Friendship"
  )

  has_many(
    :in_friendships,
    :foreign_key => :out_friend_id,
    :class_name => "Friendship"
  )

  has_many(
    :in_friends, # user's friends
    :through => :in_friendships,
    :source => :in_friend
  )

  has_many(
    :out_friends, # friends that added user
    :through => :out_friendships,
    :source => :out_friend
  )

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :username, :presence => true

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery

  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = Friendship.new({:in_friend_id => params[:user_id],
                                  :out_friend_id => current_user.id})
    @friendship.save!

    redirect_to users_url
  end

  def destroy
    @friendship = current_user.in_friendships.where(:in_friend_id => params[:user_id]).first
    @friendship.destroy

    head 200
  end

end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  def new
    @user = User.find(params[:user_id])

    render :new
  end

  def create
    @secret = current_user.authored_secrets.new(params[:secrets])
    if @secret.save
      render :json => @secret
    else
      render :text => "something is wrong!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_current_user!
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= button_to("add friend", user_friendships_url(user))%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecretShareAjax</title>
  <script src="http://underscorejs.org/underscore-min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !current_user.nil? %>
  <ul>
    <li>Logged in as: <%= current_user.username %></li>
    <li><%= button_to "Logout", session_url, :method => :delete %></li>
  </ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/secrets/_form.html.erb
<h3>Add Secret</h3>
<form action="<%= secrets_url %>" id="secrets-form" method="POST">
  <input name="secrets[title]" type="text" id="secrets-title">
  <input name="secrets[recipient_id]" type="hidden" value="<%= @user.id %>">
  
  <div id="add-tags-content"></div>
  <button id="add-tag">add another tag</button>
  <br />
  <input type="submit" value="submit">
</form>

<script type="application/json" id="bootstrapped-tags-json">
  { "tags" : <%= Tag.all.to_json.html_safe %> }
</script>

<script type="text/template" id="tags-template">
  <select name="secrets[tag_ids][]" >
    <%% _(tags).each(function(tag){ %>
      <option value="<%%= tag.id %>"><%%= tag.name %></option>
    <%% }); %>
  </select>
</script>

<script type="text/javascript">
  $("#add-tag").on("click", function(event){
    event.preventDefault();
    
    var tags = JSON.parse($("#bootstrapped-tags-json").html());
    var templateCode = $("#tags-template").html();
    var templateFn = _.template(templateCode);
    var renderedContent = templateFn(tags);

    $("#add-tags-content").append(renderedContent);
  });

</script>

app/views/secrets/new.html.erb
<form action="<%= secrets_url %>" method="POST">
  <input name="secrets[title]" type="text" id="secrets_title">
  <input name="secrets[recipient_id]" type="hidden" value="<%= @user.id %>">

  <input type="submit" value="submit">
</form>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/index.html.erb
<style>
  div.friend-buttons.can-friend button.unfriend {
    display: none;
  }

  div.friend-buttons.can-unfriend button.friend {
    display: none;
  }
</style>

<ul>
  <% @users.each do |user| %>
    <% next if user.id == current_user.id %>
    <li>
      <%= user.username %>

      <% if Friendship.can_friend?(current_user.id, user.id) %>
       <div class="friend-buttons can-friend">
        <button class="friend" data-inFriendId="<%= user.id %>" data-outFriendId="<%= current_user.id %>">add friend</button>

        <button class="unfriend" data-inFriendId="<%= user.id %>" data-outFriendId="<%= current_user.id %>">unfriend</button>
      </div>
      <% else %>
       <div class="friend-buttons can-unfriend">
        <button class="friend" data-inFriendId="<%= user.id %>" data-outFriendId="<%= current_user.id %>">add friend</button>

        <button class="unfriend" data-inFriendId="<%= user.id %>" data-outFriendId="<%= current_user.id %>">unfriend</button>
      </div>
      <% end %>
    </div>
  </li>

  <% end %>
</ul>

<script type="text/javascript">
  var toggleFriendButton = function(element){
    $(element).toggleClass('can-friend');
    $(element).toggleClass('can-unfriend');
  };

  $(".friend").on("click", function(event){
    // $(this).text("Friending...");
    var inId = $(this).attr("data-inFriendId");
    var outId = $(this).attr("data-outFriendId");
    var url = "/users/" + inId + "/friendship";
    var $div = $(this).parent();
    $.ajax({
      type: "POST",
      url: url,
      success: function(res){
        toggleFriendButton($div);
      }
    });
  });

  $(".unfriend").on("click", function(event){
    // $(this).text("unfriending...");
    var inId = $(this).attr("data-inFriendId");
    var outId = $(this).attr("data-outFriendId");
    var url = "/users/" + inId + "/friendship";
    var $div = $(this).parent();

    $.ajax({
      type: "DELETE",
      url: url,
      success: function(res){
        toggleFriendButton($div);
      }
    });
  });
</script>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h2>Secrets</h2>
<ul id="secrets">
  <% @user.received_secrets.each do |secret| %>
    <li>
      <%= secret.title %> | tags: <%= secret.tags.map { |tag| tag.name }.join(", ")%>
    </li>
  <% end %>

</ul>

<%= render 'secrets/form', :tags => Tag.all %>

<script type="text/javascript">
  $('#secrets-form').on("submit", function(event) {
    event.preventDefault();
    var data = $(this).serialize();
    console.log(data);
    $.ajax({
     type: "POST",
     url: "/secrets",
     data: data,
     success: function(resp){
       $("#secrets").prepend("<li>" + resp.title + "</li>");
       $("#secrets-title").val("");
       $("#add-tags-content").html("");
     }
    })
  });
</script>